### ISSUE TITLE
如果我想使用 sing-box 的另一个分支作为内核，我该做哪些工作？

### ISSUE THREAD

**Issue by NekoLSD** [daodao97/SingBoxClient#10]

**Comment by daodao97** [comment]
可以在 `go.mod` 修改  [https://github.com/daodao97/SingBoxClient/blob/master/go.mod#L106](https://github.com/daodao97/SingBoxClient/blob/master/go.mod#L106)  replace

在 `sb` 目录中切换到你的目标分支, 然后回到 `SingBoxClient` 执行 `go mod vendor` 即可将目标分支代码同步置本项目 `vendor` 下

然后执行 `sh ./build.sh` 编译即可

**Comment by daodao97** [comment]
因为我在本地修改的了 `github.com/getlantern/notifier => ../notifier` 项目,  增加了 `OnClick` 方法, 参见[vendor](https:github.com/daodao97/SingBoxClient/blob/master/vendor/github.com/getlantern/notifier/notifier_darwin.go#L65)

```sh
git clone https://github.com/daodao97/SingBoxClient.git
cp -rf SingBoxClient/vendor/github/getlantern/notifier ./
git clone github.com/sagernet/sing-box ./sb
# 修改 sb
cd SingBoxClient
git mod vendor
sh ./build.sh
```
